# 一、ndarray
## 1. ndarray的特性
### 多维性

In [1]:
import numpy as np

In [4]:
arr = np.array(5)  # 创建0维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

5
arr的维度：0


In [5]:
arr = np.array([1, 2, 3, 4, 5])  # 创建1维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[1 2 3 4 5]
arr的维度：1


In [8]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])  # 创建2维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[[1 2 3 4 5]
 [6 7 8 9 0]]
arr的维度：2


### 同质性

In [11]:
arr = np.array([1, 'atguigu'])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

['1' 'atguigu']


In [13]:
arr = np.array([1, 3.25])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

(2,)


## 2. ndarray的属性

In [28]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

1
arr的形状：()
arr的维度：0
元素的个数：1
数据类型：int64
矩阵的转置：1


In [27]:
arr = np.array([1, 2.5, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[1.  2.5 3. ]
arr的形状：(3,)
arr的维度：1
元素的个数：3
数据类型：float64
矩阵的转置：[1.  2.5 3. ]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 二行三列
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素的个数：6
数据类型：int64
矩阵的转置：[[1 4]
 [2 5]
 [3 6]]


## 3. ndarray的创建

In [34]:
# 基础的创建方法
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)

[1. 2. 3.]


In [36]:
# copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [38]:
# 预定义形状
# 全0、全1、未初始化、固定值
# 全0
arr1 = np.zeros((2, 3))  # 2维数组
print(arr1)
arr1 = np.zeros((2,))  # 1维数组
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0.]


In [40]:
# 全1
arr2 = np.ones((5, 5), dtype=int)
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [50]:
# 未初始化
arr3 = np.empty((3, 3))
print(arr3)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [3.22647253e-307 2.67018777e-306 1.42413555e-306]
 [1.78019082e-306 1.37959740e-306 2.29178686e-312]]


In [51]:
arr4 = np.full((3, 4), 2026)
print(arr4)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [56]:
arr5 = np.zeros_like(arr4)
print(arr5)
arr5 = np.empty_like(arr4)
print(arr5)
arr5 = np.ones_like(arr4)
print(arr5)
arr5 = np.full_like(arr4, 2027)
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [58]:
# 等差数列
arr = np.arange(1, 50, 2)  # start, end, step
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [63]:
# 等间隔数列（均分）
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [69]:
# 指数间隔数列
arr = np.logspace(0, 4, 5, base=2)
print(arr)

[ 1.  2.  4.  8. 16.]
