# 一、ndarray
## 1. ndarray的特性
### 多维性

In [7]:
import numpy as np

In [8]:
arr = np.array(5)  # 创建0维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

5
arr的维度：0


In [9]:
arr = np.array([1, 2, 3, 4, 5])  # 创建1维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[1 2 3 4 5]
arr的维度：1


In [10]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])  # 创建2维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[[1 2 3 4 5]
 [6 7 8 9 0]]
arr的维度：2


### 同质性

In [11]:
arr = np.array([1, 'atguigu'])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

['1' 'atguigu']


In [12]:
arr = np.array([1, 3.25])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

[1.   3.25]


## 2. ndarray的属性

In [13]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

1
arr的形状：()
arr的维度：0
元素的个数：1
数据类型：int64
矩阵的转置：1


In [14]:
arr = np.array([1, 2.5, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[1.  2.5 3. ]
arr的形状：(3,)
arr的维度：1
元素的个数：3
数据类型：float64
矩阵的转置：[1.  2.5 3. ]


In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 二行三列
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素的个数：6
数据类型：int64
矩阵的转置：[[1 4]
 [2 5]
 [3 6]]


## 3. ndarray的创建

In [16]:
# 基础的创建方法
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)

[1. 2. 3.]


In [17]:
# copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [18]:
# 预定义形状
# 全0、全1、未初始化、固定值
# 全0
arr1 = np.zeros((2, 3))  # 2维数组
print(arr1)
arr1 = np.zeros((2,))  # 1维数组
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0.]


In [19]:
# 全1
arr2 = np.ones((5, 5), dtype=int)
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
# 未初始化
arr3 = np.empty((3, 3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [21]:
arr4 = np.full((3, 4), 2026)
print(arr4)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [22]:
arr5 = np.zeros_like(arr4)
print(arr5)
arr5 = np.empty_like(arr4)
print(arr5)
arr5 = np.ones_like(arr4)
print(arr5)
arr5 = np.full_like(arr4, 2027)
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      2192251663480                  64                   0
                    0]
 [  29273895794114560 7147837368326828389 3689636904740271974
  3703473343834764899]
 [3630517267502084451 4135768114870038628 3762021031521562928
  3689636891066775347]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [23]:
# 等差数列
arr = np.arange(1, 50, 2)  # start, end, step
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [24]:
# 等间隔数列（均分）
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [25]:
# 指数间隔数列
arr = np.logspace(0, 4, 5, base=2)
print(arr)

[ 1.  2.  4.  8. 16.]


In [30]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [33]:
# 对角矩阵
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [35]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.58440719 0.05102788 0.25440225]
 [0.95150158 0.9356393  0.21485273]]


In [37]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (4, 5))
print(arr)

[[4.78082572 5.24364142 3.49171825 3.76200898 5.55846447]
 [4.77726396 4.18569438 5.95372268 4.91708339 5.56318723]
 [3.9666263  3.28570372 3.65345798 5.34188247 5.51272184]
 [3.75695506 4.92112427 5.08977537 3.78515075 3.20767561]]


In [38]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[16 28  4]
 [25 10  5]]


In [39]:
# 生成随机数列（正态分布）(-3到3之间)
arr = np.random.randn(2, 3)
print(arr)

[[ 0.20237538 -0.62278869 -0.22230946]
 [-1.80201169 -0.04895095  1.362285  ]]


In [64]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray的数据类型

In [66]:
# 布尔、有符号，无符号的int和float、复数
# 复数
arr = np.array([1, 2, 3, 4], dtype=np.complex64)
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## 5. 索引与切片

In [74]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr[:])
print(arr[slice(2, 15, 3)])  # start, end, step
print(arr[(arr > 10) & (arr < 70)])  # 布尔索引

[12 86 28 72 24 38 55 34  7 13 37 93  7 65  8 47  3 27 71 51]
[28 38  7 93  8]
[12 28 24 38 55 34 13 37 65 47 27 51]


In [77]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[86 39 55 87 39 72 34 24]
 [78 47 44 25 31 65 34  5]
 [94 37 78 28 71 35 98 33]
 [ 6 94 40 17 37 72 60 76]]


In [83]:
print(arr[0, 3])
print(arr[1:3, 1:4])
print(arr[2][arr[2] > 50])
print(arr[:, 3])

87
[[47 44 25]
 [37 78 28]]
[94 78 71 98]
