# 一、ndarray
## 1. ndarray的特性

### 多维性

In [2]:
import numpy as np

In [3]:
arr = np.array(5)  # 创建0维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

5
arr的维度：0


In [4]:
arr = np.array([1, 2, 3, 4, 5])  # 创建1维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[1 2 3 4 5]
arr的维度：1


In [5]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])  # 创建2维的ndarray
print(arr)
print(f'arr的维度：{arr.ndim}')

[[1 2 3 4 5]
 [6 7 8 9 0]]
arr的维度：2


### 同质性

In [6]:
arr = np.array([1, 'atguigu'])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

['1' 'atguigu']


In [7]:
arr = np.array([1, 3.25])  # 不同的数据类型会被强制转换成相同的类型
print(arr)

[1.   3.25]


## 2. ndarray的属性

In [8]:
arr = np.array(1)
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

1
arr的形状：()
arr的维度：0
元素的个数：1
数据类型：int64
矩阵的转置：1


In [9]:
arr = np.array([1, 2.5, 3])
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[1.  2.5 3. ]
arr的形状：(3,)
arr的维度：1
元素的个数：3
数据类型：float64
矩阵的转置：[1.  2.5 3. ]


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 二行三列
print(arr)
print(f'arr的形状：{arr.shape}')
print(f'arr的维度：{arr.ndim}')
print(f'元素的个数：{arr.size}')
print(f'数据类型：{arr.dtype}')
print(f'矩阵的转置：{arr.T}')

[[1 2 3]
 [4 5 6]]
arr的形状：(2, 3)
arr的维度：2
元素的个数：6
数据类型：int64
矩阵的转置：[[1 4]
 [2 5]
 [3 6]]


## 3. ndarray的创建

In [11]:
# 基础的创建方法
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr)

[1. 2. 3.]


In [12]:
# copy
arr1 = np.copy(arr)
print(arr1)

[1. 2. 3.]


In [13]:
# 预定义形状
# 全0、全1、未初始化、固定值
# 全0
arr1 = np.zeros((2, 3))  # 2维数组
print(arr1)
arr1 = np.zeros((2,))  # 1维数组
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0.]


In [14]:
# 全1
arr2 = np.ones((5, 5), dtype=int)
print(arr2)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [15]:
# 未初始化
arr3 = np.empty((3, 3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
arr4 = np.full((3, 4), 2026)
print(arr4)

[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]


In [17]:
arr5 = np.zeros_like(arr4)
print(arr5)
arr5 = np.empty_like(arr4)
print(arr5)
arr5 = np.ones_like(arr4)
print(arr5)
arr5 = np.full_like(arr4, 2027)
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[      1902373352520                  57                   0
                    0]
 [  29273895794114560 3760061921801430379 3257008740271010658
  4120851027865330998]
 [7218479865915845944 3919601942797706342 7162263158365041456
  8462385098680267893]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


In [18]:
# 等差数列
arr = np.arange(1, 50, 2)  # start, end, step
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [19]:
# 等间隔数列（均分）
arr = np.linspace(0, 100, 5, dtype=int)
print(arr)
arr = np.arange(0, 101, 25)
print(arr)

[  0  25  50  75 100]
[  0  25  50  75 100]


In [20]:
# 指数间隔数列
arr = np.logspace(0, 4, 5, base=2)
print(arr)

[ 1.  2.  4.  8. 16.]


In [21]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3, 4, dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [22]:
# 对角矩阵
arr = np.diag([1, 2, 3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [23]:
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(2, 3)
print(arr)

[[0.53708501 0.62655948 0.94684682]
 [0.44461973 0.4499581  0.24352104]]


In [24]:
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (4, 5))
print(arr)

[[5.28049723 4.82659053 5.60313066 4.49898652 4.1023543 ]
 [4.94675282 4.45701191 3.7462411  4.97531989 4.75565624]
 [5.77387417 3.11932143 5.01125532 3.94357794 4.63987513]
 [4.68451145 3.30478325 5.46954282 3.08719311 5.10473759]]


In [25]:
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 30, (2, 3))
print(arr)

[[11  9  3]
 [15  8 21]]


In [26]:
# 生成随机数列（正态分布）(-3到3之间)
arr = np.random.randn(2, 3)
print(arr)

[[ 0.80520742  0.1444378   0.00800074]
 [-0.25015428 -0.12375529 -1.10985016]]


In [27]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1, 10, (2, 5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 4. ndarray的数据类型

In [28]:
# 布尔、有符号，无符号的int和float、复数
# 复数
arr = np.array([1, 2, 3, 4], dtype=np.complex64)
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


## 5. 索引与切片

In [29]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 20)
print(arr[:])
print(arr[slice(2, 15, 3)])  # start, end, step
print(arr[(arr > 10) & (arr < 70)])  # 布尔索引

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]
[17  7 76  4 62]
[17 63 17 27 14 59 26 62 58 33]


In [30]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (4, 8))
print(arr)

[[11  7 76 19  4 78 18 44]
 [17 19 80 91 60 72 76 30]
 [46  7 64 79 25 19 94 34]
 [79 43 95  4 19 71 53 23]]


In [31]:
print(arr[0, 3])
print(arr[1:3, 1:4])
print(arr[2][arr[2] > 50])
print(arr[:, 3])

19
[[19 80 91]
 [ 7 64 79]]
[64 79 94]
[19 91 79  4]


## 6. ndarray的运算

In [40]:
# 算术运算
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)

[5 7 9]
[ 4 10 18]


In [37]:
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
print('a:\n', a)
print('b:\n', b)
print('a + b:\n', a + b)
print('a - b:\n', a - b)
print('a * b:\n', a * b)
print('a / b:\n', a / b)

a:
 [[3 5 6]
 [4 8 2]
 [3 4 7]]
b:
 [[6 5 5]
 [2 9 8]
 [2 3 4]]
a + b:
 [[ 9 10 11]
 [ 6 17 10]
 [ 5  7 11]]
a - b:
 [[-3  0  1]
 [ 2 -1 -6]
 [ 1  1  3]]
a * b:
 [[18 25 30]
 [ 8 72 16]
 [ 6 12 28]]
a / b:
 [[0.5        1.         1.2       ]
 [2.         0.88888889 0.25      ]
 [1.5        1.33333333 1.75      ]]


In [41]:
# 广播机制
# 同一维度：
a = np.array([1, 2, 3])  # 1*3
b = np.array([[4], [5], [6]])  # 3*1
print(a + b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [44]:
# 矩阵运算（线代）
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[4, 5, 6], [7, 8, 9], [1, 2, 3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


## 7. 常用函数

In [47]:
x = 100
# 基本数学
np.sqrt(x)          # 计算x的平方根
np.exp(x)           # 计算自然常数e的x次幂（e^x）
np.log(x)           # 计算x的自然对数（以e为底）
np.sin(x)           # 计算x的正弦值（x以弧度为单位）
np.abs(x)           # 计算x的绝对值
np.power(2, 4)      # 计算第一个参数的第二个参数次幂（2^4）
np.round(x, 2)      # 将x四舍五入到指定的小数位数（此处为2位）

np.int64(100)

In [48]:
# 统计
x = np.array([10, 20, 30, 40, 50])  # 补充示例数组，方便理解函数效果
np.sum(x)               # 计算数组中所有元素的总和
np.mean(x)              # 计算数组元素的算术平均值
np.median(x)            # 计算数组元素的中位数（将数据排序后取中间值）
np.std(x)               # 计算数组元素的标准差（衡量数据离散程度，默认除以n）
np.var(x)               # 计算数组元素的方差（标准差的平方）
np.min(x)               # 找出数组中的最小值
np.max(x)               # 找出数组中的最大值
np.percentile(x, 100)   # 计算数组在指定百分位上的数值（100分位即最大值）

np.float64(100.0)

In [49]:
# 比较运算函数
np.greater(10, 20)          # 比较第一个参数是否大于第二个参数，返回布尔值（10>20 → False）
np.less(10, 20)             # 比较第一个参数是否小于第二个参数，返回布尔值（10<20 → True）
np.equal(10, 20)            # 比较两个参数是否相等，返回布尔值（10==20 → False）

# 逻辑运算函数
np.logical_and(10, 20)      # 对两个参数做逻辑与运算（非0值视为True），10和20均非0 → True
z = np.array([-2, -1, 0, 1, 2])
np.where(z < 0, 0, z)  # 小于0的替换为0，否则保留原值 → [0 0 0 1 2]

np.True_

In [55]:
# 定义示例数组，方便演示函数效果
x = np.array([1, 2, 2, 3, 3, 3, 4])
y = np.array([2, 4, 6])

# 数组去重与匹配判断函数
np.unique(x)               # 去除数组中的重复元素，返回排序后的唯一值数组 → [1 2 3 4]
# np.in1d(x, y)              # 判断x中的每个元素是否存在于y中，返回布尔值数组 → [False True True False False False True]

array([1, 2, 3, 4])

In [53]:
# 定义示例数组，方便演示排序效果
x = np.array([3, 1, 4, 2, 5])
# 先复制原数组，避免原地排序影响后续演示
x_copy = x.copy()

# 排序相关函数/方法
np.sort(x)               # 对数组进行升序排序，返回排序后的新数组（原数组x保持不变）→ [1 2 3 4 5]
x_copy.sort()            # 数组的原地排序方法，直接修改原数组（无返回值），排序后x_copy变为 [1 2 3 4 5]
np.argsort(x)            # 返回数组升序排序的索引值数组（原数组不变）→ [1 3 0 2 4]（表示x[1]=1是最小值，x[3]=2次之）
np.lexsort((x, [5,4,3,2,1]))  # 多键字典序排序，返回排序索引（按最后一个参数为主键，向前依次为辅键）→ [4 3 2 1 0]

array([4, 3, 2, 1, 0])

In [56]:
# 定义示例数组（避免单数值导致函数无意义/报错）
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([7, 8, 9])
z = np.array([1, np.nan, 3, np.nan, 5])  # 包含NaN值的数组

# 数组操作函数（修正参数错误+添加功能注释）
np.concatenate((x, y))     # 拼接多个数组（需传入数组元组，而非单数值），返回拼接后的新数组 → [1 2 3 4 5 6 7 8 9]
np.split(x, 2)             # 将数组按指定份数/位置拆分（拆分份数需能整除数组长度），返回拆分后的数组列表 → [array([1,2,3]), array([4,5,6])]
np.reshape(x, (2, 3))      # 将数组重塑为指定形状（元素总数需匹配），返回新形状数组 → [[1 2 3],[4 5 6]]
np.copy(x)                 # 生成数组的深拷贝（新数组与原数组独立，修改互不影响），返回拷贝后的新数组
np.isnan(z)                # 逐元素判断是否为NaN（非数字），返回布尔值数组 → [False  True False  True False]

array([False,  True, False,  True, False])

# numpy科学计算综合练习