In [3]:
import numpy as np

In [6]:
'''
题目1：矩阵运算
A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]
计算 A + B 和 A * B（逐元素乘法）
计算 A 和 B 的矩阵乘法（点积）
'''
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A + B)
print(A * B)
print(A @ B)
print(np.dot(A, B))

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [13]:
'''
题目2：随机数据生成
生成一个(3, 4)的随机整数数组，范围[0, 10)
计算 每列的最大值和每行的最小值
将数组中的所有奇数替换为 -1
'''
np.random.seed(0)
arr = np.random.randint(0, 10, (3, 4))
print(arr)
print('每列的最大值：', np.max(arr, axis=0))
print('每行的最小值：', np.min(arr, axis=1))
print(np.where(arr % 2 == 1, -1, arr))  # where和三元运算符很像 ? :
print(arr)
arr[arr %2 == 1] = -1
print(arr)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
每列的最大值： [7 9 7 6]
每行的最小值： [0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [24]:
'''
题目3：数组变形
创建一个1到12的一维数组，并转换为(3, 4)的二维数组
计算每行与每列的平均值
将数组展平为一维数组
'''
# arr = np.array([i for i in range(1, 13)])
arr = np.arange(1, 13)
print(arr)
arr = np.reshape(arr, (3, 4))
print(arr)
print('每行的和：', np.sum(arr, axis=1))
print('每列的平均值：', np.mean(arr, axis=0))
print(np.reshape(arr, (12)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行的和： [10 26 42]
每列的平均值： [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
'''
题目4：布尔索引
生成一个(5, 5)的随机数组，范围[0, 20)
找出数组中大于10的元素
将所有大于10的元素替换为0
'''
np.random.seed(0)
arr = np.random.randint(0, 20, (5, 5))
print(arr)
print(arr[arr > 10])
arr[arr > 10] = 0
print(arr)

[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[0 0 0 3 3]
 [7 9 0 0 4]
 [6 0 1 6 7]
 [0 0 5 0 8]
 [9 0 0 0 5]]


In [31]:
'''
题目5：统计函数应用
某公司6个月的销售额（万元）为[120, 135, 110, 125, 130, 140]
计算总和、均值、方差
找出销售额最高的月份和最低的月份
'''
money = np.array([120, 135, 110, 125, 130, 140])
print('总和：', np.sum(money))
print('平均值：', np.mean(money))
print('方差：', np.var(money))
print('最高的月份', np.argmax(money) + 1)
print('最第的月份', np.argmin(money) + 1)

总和： 760
平均值： 126.66666666666667
方差： 97.22222222222223
最高的月份 6
最第的月份 3


In [34]:
'''
题目6：数组的拼接
水平拼接
垂直拼接
'''
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.concat([A, B])
print(C)
print(np.reshape(C, (2, 3)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [36]:
'''
题目7：唯一值与排序
给定数组[2, 1, 2, 3, 1, 4, 3]
找出数组中的唯一值并排序
计算每个唯一值出现的次数
'''
arr = np.array([2, 1, 2, 3, 1, 4, 3])
u_arr, counts = np.unique(arr, return_counts=True)
print(u_arr)
print(counts)

[1 2 3 4]
[2 2 2 1]
